### ISSUE TITLE
Couldn't install it on my mac

### ISSUE THREAD

**Issue by wenmengliu** [veugene/data_tools#1]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-wunoiq9a/

Thanks!!!

**Comment by veugene** [comment]
I didn't include an installer but I think I should. I might do so this weekend.

The way I use this library and others is by putting a link to the internal `data_tools` folder in a custom location that is in my `PYTHONPATH`.

An installer would make it simpler for people to use, though.

**Comment by wenmengliu** [comment]
Thanks so much!!! Yeah, it would be easier for users to install it. I am following your amazing work on LTiS 2017 challenge. It is so helpful for me because I just start my research on medical image analysis. Thanks for sharing your clean and organized codes!!!! It is so helpful for me.

**Comment by veugene** [comment]
Great to hear that it's helpful :)

**Comment by wenmengliu** [comment]
Hi Eugene,

If I have some questions about LiTS 2017 challenge,  may I ask them for you via email? (I am sorry I will bother you about that 😭). Now I am a first year graduate at University of Victoria (hopefully you hear about it ☺️). I do love to explore the medical image analysis combined with deep learning techniques. It is a new adventure for me✌️

Thanks💕💕💕

Cheers,
Crystal

**Comment by veugene** [comment]
Yes, no problem -- I'll email you.
