### ISSUE TITLE
Need some update 

### ISSUE THREAD

**Issue by wenmengliu** [veugene/data_tools#2]
Hi Veugene, 
I am wondering whether you have already changed something on this repo. This repo is so good for processing data but I think it might need some update or offer some info about libraries info. Maybe include a `requriment.txt` file will be perfect. When I used this repo, there is a conflict between zarr library and progressbar.So I install progressbar2 while it doesn't have attribute about `currval`. Hopefully, you could share it with your update!

Thanks
Crystal

**Comment by veugene** [comment]
Yes, you're right - I should add at least a requirements file or an installer.

**Comment by wenmengliu** [comment]
I am looking forward to your enhanced version :)
